name: vieiros
description: GPX trails tools and tracking

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
version: 1.5.10+160

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  file_picker: ^10.3.3
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  flutter:
    sdk: flutter

  flutter_local_notifications: ^19.4.1
  flutter_tts: ^4.2.3
  fl_chart: ^1.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  gpx: ^2.2.2
  image: ^4.5.4
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  share_plus: ^11.1.0
  sunrise_sunset_calc: ^3.0.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
